CREATE TABLE pending_users (
    id INT(11) NOT NULL AUTO_INCREMENT,
    uniqueID VARCHAR(100) NOT NULL,
    first_name VARCHAR(50) NOT NULL,
    middle_name VARCHAR(50) DEFAULT NULL,
    last_name VARCHAR(50) NOT NULL,
    id_number VARCHAR(50) NOT NULL,
    address TEXT NOT NULL,
    gender VARCHAR(50) NOT NULL,
    age INT(11) NOT NULL,
    phone_number VARCHAR(12) NOT NULL,
    stud_email VARCHAR(100) NOT NULL,
    role VARCHAR(50) NOT NULL,
    password VARCHAR(255) NOT NULL,
    online_offlineStatus VARCHAR(20) NOT NULL DEFAULT 'Offline',
    sis_document VARCHAR(255) DEFAULT NULL,
    access_level INT(11) NOT NULL DEFAULT 0,
    verification_code VARCHAR(6) NOT NULL,
    verify_status VARCHAR(20) NOT NULL DEFAULT 'Not Verified',
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uniqueID (uniqueID),
    UNIQUE KEY id_number (id_number),
    UNIQUE KEY phone_number (phone_number),
    UNIQUE KEY stud_email (stud_email)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;